local a={
MAX_NUMBER=4,

RepairEquipmentPos={
EQUIPMENT_INVENTORY.MELEE_WEAPON,
EQUIPMENT_INVENTORY.RANGE_WEAPON,
EQUIPMENT_INVENTORY.CHEST,
EQUIPMENT_INVENTORY.HELM,
EQUIPMENT_INVENTORY.WAIST,
EQUIPMENT_INVENTORY.PANTS,
EQUIPMENT_INVENTORY.BOOTS,
EQUIPMENT_INVENTORY.BANGLE,
},

AllEquipmentPos={
EQUIPMENT_INVENTORY.HELM,
EQUIPMENT_INVENTORY.CHEST,
EQUIPMENT_INVENTORY.BANGLE,
EQUIPMENT_INVENTORY.WAIST,
EQUIPMENT_INVENTORY.PANTS,
EQUIPMENT_INVENTORY.BOOTS,
EQUIPMENT_INVENTORY.WAIST_EXTEND,
EQUIPMENT_INVENTORY.AMULET,
EQUIPMENT_INVENTORY.PENDANT,
EQUIPMENT_INVENTORY.LEFT_RING,
EQUIPMENT_INVENTORY.RIGHT_RING,
EQUIPMENT_INVENTORY.MELEE_WEAPON,
EQUIPMENT_INVENTORY.RANGE_WEAPON,
EQUIPMENT_INVENTORY.ARROW,
EQUIPMENT_INVENTORY.BACK_EXTEND,
},
}